# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06d194e4ed4a90489d26117b117c01bb22102a0a7069999f7b7ad69593dd9378d63f2cdbe0fe596266077035adce1c5c7b051667ca7f1d224ac0b1681f61c0d8

test:
  secret_key_base: cb56e8b4e0ef42e80fda751d19ad96abd3f3696f87869efec6edc152f2aede1cd311e286e596bb4826b0183bb815737b1b1d6401fc829e7c995ec8b59de80c73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
